# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=15)),
                ('genre_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_description', models.CharField(max_length=500)),
                ('release_year', models.PositiveSmallIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('movie_price', models.SmallIntegerField(default=0)),
                ('movie_teaser_url', models.CharField(max_length=100)),
                ('movie_thumbnail', models.FileField(upload_to='')),
                ('movie_file', models.FileField(upload_to='')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Genre')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
