# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='user_id',
            new_name='user',
        ),
    ]
