# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20161007_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_description',
            field=models.CharField(max_length=500),
        ),
    ]
