# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=300),
        ),
    ]
