# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(max_length=15)),
                ('value', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
