# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_refillment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refillment',
            new_name='Serial',
        ),
    ]
