# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20161124_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='value',
            new_name='price',
        ),
    ]
