# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20161124_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
